import type { CrudModuleConfig, NavModule } from "../../types/app";

export const navModules: NavModule[] = [
  { key: "dashboard", title: "Dashboard", path: "/", permission: "reports.read" },
  { key: "products", title: "Products", path: "/products", permission: "product.read" },
  { key: "inventory", title: "Inventory", path: "/inventory", permission: "inventory.read" },
  { key: "customers", title: "Customers", path: "/customers", permission: "customer.read" },
  { key: "suppliers", title: "Suppliers", path: "/suppliers", permission: "supplier.read" },
  { key: "billing", title: "Billing", path: "/billing", permission: "billing.read" },
  { key: "pos", title: "POS", path: "/pos", permission: "pos.manage" },
  { key: "reports", title: "Reports", path: "/reports", permission: "reports.read" },
  { key: "employees", title: "Employees", path: "/employees", permission: "employee.read" },
  { key: "attendance", title: "Attendance", path: "/attendance", permission: "employee.read" },
  { key: "communication", title: "Communication", path: "/communication", permission: "notification.inbox.read" },
  { key: "documents", title: "Documents", path: "/documents", permission: "document.read" },
  { key: "settings", title: "Business Settings", path: "/settings", permission: "business.read" },
  { key: "audit", title: "Audit Logs", path: "/audit-logs", permission: "monitoring.audit.read" },
  { key: "monitoring", title: "Monitoring", path: "/monitoring", permission: "monitoring.read" },
];

export const crudModules: Record<string, CrudModuleConfig> = {
  products: {
    title: "Products",
    endpoint: "/products",
    permissionRead: "product.read",
    permissionManage: "product.manage",
    fields: [
      { key: "name", label: "Name", required: true },
      { key: "sku", label: "SKU" },
      { key: "barcode", label: "Barcode" },
      { key: "price", label: "Price", type: "number" },
      { key: "cost", label: "Cost", type: "number" },
    ],
    searchParam: "q",
    supportsRestore: true,
    exportPath: "/products/bulk-export",
    importPath: "/products/bulk-import",
  },
  customers: {
    title: "Customers",
    endpoint: "/customers",
    permissionRead: "customer.read",
    permissionManage: "customer.manage",
    fields: [
      { key: "name", label: "Name", required: true },
      { key: "phone", label: "Phone" },
      { key: "email", label: "Email", type: "email" },
      { key: "creditLimit", label: "Credit Limit", type: "number" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    searchParam: "q",
    supportsRestore: true,
    exportPath: "/customers/export",
    importPath: "/customers/import",
  },
  suppliers: {
    title: "Suppliers",
    endpoint: "/suppliers",
    permissionRead: "supplier.read",
    permissionManage: "supplier.manage",
    fields: [
      { key: "name", label: "Name", required: true },
      { key: "phone", label: "Phone" },
      { key: "email", label: "Email", type: "email" },
      { key: "creditLimit", label: "Credit Limit", type: "number" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    searchParam: "q",
    supportsRestore: true,
    exportPath: "/suppliers/export",
    importPath: "/suppliers/import",
  },
  employees: {
    title: "Employees",
    endpoint: "/employees",
    permissionRead: "employee.read",
    permissionManage: "employee.manage",
    fields: [
      { key: "name", label: "Name", required: true },
      { key: "email", label: "Email", type: "email" },
      { key: "phone", label: "Phone" },
      { key: "role", label: "Role" },
    ],
    searchParam: "q",
  },
};
