apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smartbiz-backend
  namespace: smartbiz
spec:
  selector:
    matchLabels:
      app: smartbiz-backend
  namespaceSelector:
    matchNames:
      - smartbiz
  endpoints:
    - port: http
      path: /api/v1/monitoring/metrics
      interval: 30s
