import "../../models/module_item.dart";

class AppConfig {
  static const String apiBasePath = "/api/v1";
  static const String sessionStorageKey = "smartbiz_mobile_session";
  static const String authPinKey = "smartbiz_mobile_pin";

  static const List<String> roles = [
    "BUSINESS_OWNER",
    "MANAGER",
    "CASHIER",
    "INVENTORY_MANAGER",
    "PURCHASE_MANAGER",
    "SALES_MANAGER",
    "HR_MANAGER",
    "ACCOUNTANT",
    "EMPLOYEE",
    "SUPER_ADMIN",
    "OWNER",
  ];

  static const List<ModuleItem> modules = [
    ModuleItem(key: "dashboard", title: "Dashboard", route: "/dashboard"),
    ModuleItem(key: "products", title: "Products", route: "/modules/products", permission: "product.read"),
    ModuleItem(key: "inventory", title: "Inventory", route: "/modules/inventory", permission: "inventory.read"),
    ModuleItem(key: "customers", title: "Customers", route: "/modules/customers", permission: "customer.read"),
    ModuleItem(key: "suppliers", title: "Suppliers", route: "/modules/suppliers", permission: "supplier.read"),
    ModuleItem(key: "billing", title: "Billing", route: "/modules/billing", permission: "billing.read"),
    ModuleItem(key: "reports", title: "Reports", route: "/modules/reports", permission: "reports.read"),
    ModuleItem(key: "ai-platform", title: "AI Platform", route: "/modules/ai-platform", permission: "reports.read"),
    ModuleItem(key: "employees", title: "Employees", route: "/modules/employees", permission: "employee.read"),
    ModuleItem(key: "attendance", title: "Attendance", route: "/modules/attendance", permission: "attendance.read"),
    ModuleItem(key: "leave", title: "Leave", route: "/modules/leave", permission: "leave.read"),
    ModuleItem(key: "payroll", title: "Payroll", route: "/modules/payroll", permission: "payroll.read"),
    ModuleItem(key: "communication", title: "Communication", route: "/modules/communication", permission: "notification.read"),
    ModuleItem(key: "files", title: "Files", route: "/modules/files", permission: "document.read"),
    ModuleItem(key: "business-settings", title: "Business Settings", route: "/modules/business-settings", permission: "business.read"),
    ModuleItem(key: "notifications", title: "Notifications", route: "/notifications", permission: "notification.read"),
    ModuleItem(key: "support", title: "Support", route: "/modules/support"),
  ];

  static const Map<String, List<String>> roleToModuleKeys = {
    "SUPER_ADMIN": [
      "dashboard",
      "products",
      "inventory",
      "customers",
      "suppliers",
      "billing",
      "reports",
      "ai-platform",
      "employees",
      "attendance",
      "leave",
      "payroll",
      "communication",
      "files",
      "business-settings",
      "notifications",
      "support",
    ],
    "BUSINESS_OWNER": [
      "dashboard",
      "products",
      "inventory",
      "customers",
      "suppliers",
      "billing",
      "reports",
      "ai-platform",
      "employees",
      "attendance",
      "leave",
      "payroll",
      "communication",
      "files",
      "business-settings",
      "notifications",
      "support",
    ],
    "OWNER": [
      "dashboard",
      "products",
      "inventory",
      "customers",
      "suppliers",
      "billing",
      "reports",
      "ai-platform",
      "employees",
      "attendance",
      "leave",
      "payroll",
      "communication",
      "files",
      "business-settings",
      "notifications",
      "support",
    ],
    "MANAGER": ["dashboard", "products", "inventory", "customers", "suppliers", "billing", "reports", "ai-platform", "communication", "files", "notifications", "support"],
    "CASHIER": ["dashboard", "billing", "customers", "products", "notifications"],
    "INVENTORY_MANAGER": ["dashboard", "products", "inventory", "suppliers", "reports", "ai-platform", "notifications"],
    "PURCHASE_MANAGER": ["dashboard", "inventory", "suppliers", "reports", "ai-platform", "files"],
    "SALES_MANAGER": ["dashboard", "billing", "customers", "reports", "ai-platform", "communication"],
    "HR_MANAGER": ["dashboard", "employees", "attendance", "leave", "payroll", "communication"],
    "ACCOUNTANT": ["dashboard", "billing", "reports", "ai-platform", "payroll", "files"],
    "EMPLOYEE": ["dashboard", "attendance", "leave", "notifications", "profile"],
  };
}
