apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartbiz-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: smartbiz-frontend
  template:
    metadata:
      labels:
        app: smartbiz-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.images.frontend }}
          ports:
            - containerPort: {{ .Values.frontend.servicePort }}
          resources:
{{ toYaml .Values.frontend.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: smartbiz-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: smartbiz-frontend
  ports:
    - name: http
      port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.servicePort }}
